#ifndef EDF_ESC_CHANNEL_CONFIG_H
#define EDF_ESC_CHANNEL_CONFIG_H
#define EDF_ESC_CHANNEL_ID 'A'
#define EDF_ESC_SPI_CS_PIN 24
#define EDF_ESC_DEFAULT_PWM_HZ 16000u
#define EDF_ESC_DEFAULT_POLE_COUNT 4u
#define EDF_ESC_HIGH_POWER_UNLOCKED 0
#endif
